# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: quran-core 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "quran-core".freeze
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Naveed Ahmad".freeze]
  s.date = "2019-03-07"
  s.description = "Core models for Quran api, community and Quran app".freeze
  s.email = "naveedahmada036@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "db/schema.rb",
    "lib/quran_core.rb",
    "lib/quran_core/models/api_core_record.rb",
    "lib/quran_core/models/audio_file.rb",
    "lib/quran_core/models/author.rb",
    "lib/quran_core/models/chapter.rb",
    "lib/quran_core/models/chapter_info.rb",
    "lib/quran_core/models/char_type.rb",
    "lib/quran_core/models/concerns/.keep",
    "lib/quran_core/models/concerns/language_filterable.rb",
    "lib/quran_core/models/data_source.rb",
    "lib/quran_core/models/foot_note.rb",
    "lib/quran_core/models/juz.rb",
    "lib/quran_core/models/language.rb",
    "lib/quran_core/models/lemma.rb",
    "lib/quran_core/models/media_content.rb",
    "lib/quran_core/models/recitation.rb",
    "lib/quran_core/models/recitation_style.rb",
    "lib/quran_core/models/reciter.rb",
    "lib/quran_core/models/resource_content.rb",
    "lib/quran_core/models/resource_content_stat.rb",
    "lib/quran_core/models/root.rb",
    "lib/quran_core/models/stem.rb",
    "lib/quran_core/models/tafsir.rb",
    "lib/quran_core/models/token.rb",
    "lib/quran_core/models/topic.rb",
    "lib/quran_core/models/translated_name.rb",
    "lib/quran_core/models/translation.rb",
    "lib/quran_core/models/transliteration.rb",
    "lib/quran_core/models/verse.rb",
    "lib/quran_core/models/verse_lemma.rb",
    "lib/quran_core/models/verse_root.rb",
    "lib/quran_core/models/verse_stem.rb",
    "lib/quran_core/models/word.rb",
    "lib/quran_core/models/word_corpus.rb",
    "lib/quran_core/models/word_lemma.rb",
    "lib/quran_core/models/word_root.rb",
    "lib/quran_core/models/word_stem.rb",
    "quran-core.gemspec"
  ]
  s.homepage = "http://github.com/quran/quran-core".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.1".freeze
  s.summary = "Quran core models".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<pg>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<activerecord>.freeze, ["~> 6.0.0.beta1"])
      s.add_runtime_dependency(%q<excon>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<elasticsearch>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<elasticsearch-model>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<elasticsearch-rails>.freeze, [">= 0"])
      s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    else
      s.add_dependency(%q<pg>.freeze, [">= 0"])
      s.add_dependency(%q<activerecord>.freeze, ["~> 6.0.0.beta1"])
      s.add_dependency(%q<excon>.freeze, [">= 0"])
      s.add_dependency(%q<elasticsearch>.freeze, [">= 0"])
      s.add_dependency(%q<elasticsearch-model>.freeze, [">= 0"])
      s.add_dependency(%q<elasticsearch-rails>.freeze, [">= 0"])
      s.add_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<pg>.freeze, [">= 0"])
    s.add_dependency(%q<activerecord>.freeze, ["~> 6.0.0.beta1"])
    s.add_dependency(%q<excon>.freeze, [">= 0"])
    s.add_dependency(%q<elasticsearch>.freeze, [">= 0"])
    s.add_dependency(%q<elasticsearch-model>.freeze, [">= 0"])
    s.add_dependency(%q<elasticsearch-rails>.freeze, [">= 0"])
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

